version: '3'
services:
  trybesocialdb:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trybesocialdb
      POSTGRES_PASSWORD: Tryber@123
      POSTGRES_DB: trybesocialdb

  server:
    build: ./server
    container_name: trybe_social_server
    volumes:
      - ./server:/usr/server
    ports: 
      - 3333:3333
    command: bash -c "npx prisma migrate dev && npx ts-node-dev --transpile-only --ignore-watch node_modules --respawn src/server.ts"
    env_file:
      - ./server/.env
    links:
      - trybesocialdb
    depends_on:
      - trybesocialdb

  client:
    build: ./client
    container_name: trybe_social_client
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/client
    links:
      - server
    depends_on:
      - server