version: '3'
services:
  trybesocialdb:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trybesocialdb
      POSTGRES_PASSWORD: Tryber@123
      POSTGRES_DB: trybesocialdb

  server:
    build: .
    container_name: trybe_social_server
    volumes:
      - .:/user/server
    ports: 
      - 3333:3333
    command: yarn dev
    links:
      - trybesocialdb
    depends_on:
      - trybesocialdb