import Head from 'next/head';
import { useRouter } from 'next/router';
import { MouseEvent, useState } from 'react';

export default function Login() {
  const { push } = useRouter()
  const [user, setUser] = useState('');
  const [password, setPassword] = useState('');

  const handleClick = async (
    e: MouseEvent<HTMLButtonElement, globalThis.MouseEvent>
  ) => {
    e.preventDefault();

    const URL = process.env.URL || 'http://localhost:3333';

    const body = JSON.stringify({
      email: user,
      password,
    })

    const response = await fetch(`${URL}/auth/signin`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: body,
    }).then(data => data.json()) as { acess_token: string} | any;

    if(response.acess_token) return push('/main-page')
    alert("acesso negado");
  };

  return (
    <div>
      <Head>
        <title>Login - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <form action=''>
        <h1 className='text-3xl font-bold'>Login</h1>
        <input
          type='text'
          name='user'
          className='p-1 border-2 m-2 border-black'
          value={user}
          onChange={({ target }) => setUser(target.value)}
          id='user'
        />
        <input
          type='password'
          name='password'
          className='p-1 border-2 m-2 border-black'
          value={password}
          onChange={({ target }) => setPassword(target.value)}
          id='password'
        />
        <button
          onClick={handleClick}
          type='submit'
          className='px-1 py-0.5 border-2 m-2 border-black'
        >
          Login
        </button>
        <button
          onClick={() => push('/cadastro')}
          type='submit'
          className='px-1 py-0.5 border-2 m-2 border-black'
        >
          Quero me Cadastrar
        </button>
      </form>
    </div>
  );
}
