version: '3'
services:
  server:
    build: .
    ports: 
      - 3333:3333
    command: yarn dev

#  trybesocialdb:
#    image: postgres:13-alpine
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: trybesocialdb
#      POSTGRES_PASSWORD: Tryber@123
#      POSTGRES_DB: trybesocialdb
#
  
#    links:
#      - trybesocialdb
#    depends_on:
#      - trybesocialdb