import Head from 'next/head';
import React from 'react';
import Header from '../../components/Header';

export default function index() {
  return (
    <div>
      <Head>
        <title>Main Page - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h1>Main Page</h1>
    </div>
  );
}
