import { GetServerSideProps, GetServerSidePropsResult } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react';
import Header from '../../components/Header';
import { useAuth } from '../../hooks/useAuth';

export default function MainPage() {
  const { authorized, email } = useAuth();
  const { replace } = useRouter();

  /* useEffect(() => {
    if (!authorized) replace('/login');
  }, [authorized, replace]); */

  return (
    <div>
      <Head>
        <title>Main Page - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h1>Main Page</h1>
      <h2>Você está logado com o email: {email}</h2>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const { tokenAt, tokenRt, userEmail } = req.cookies;

  if (!tokenRt || !userEmail) {
    return {
      props: {},
      redirect: {
        destination: '/login',
      },
    };
  }

  const response = await fetch(
    `http://localhost:3333/auth/refresh/${userEmail}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'token': tokenRt,
      },
    }
  );

  const tokens = await response.json();

  if (tokens.refresh_token)
    return {
      props: {},
      redirect: {
        destination: '/login',
      },
    };

  return {
    props: { userEmail },
  };
};
