import Head from 'next/head';
import { useRouter } from 'next/router';
import { MouseEvent, useState } from 'react';

export default function Login() {
  const { push } = useRouter()
  const [user, setUser] = useState('');
  const [password, setPassword] = useState('');

  const handleClick = async (
    e: MouseEvent<HTMLButtonElement, globalThis.MouseEvent>
  ) => {
    e.preventDefault();

    const URL = process.env.URL || 'http://localhost:3333';

    const body = JSON.stringify({
      email: user,
      password,
    })

    const response = await fetch(`${URL}/auth/signup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: body,
    }).then(data => data.json()) as { acess_token: string} | any;

    if(response.acess_token) return push('/login')
    alert("usuário já existe");
  };

  return (
    <div>
      <Head>
        <title>Login - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <form action=''>
        <h1 className='text-3xl font-bold'>Login</h1>
        <label htmlFor="user">
          email
          <input
            type='text'
            name='user'
            className='p-1 border-2 m-2 border-black'
            value={user}
            onChange={({ target }) => setUser(target.value)}
            id='user'
          />
        </label>
        <label htmlFor="password">
          senha
          <input
            type='password'
            name='password'
            className='p-1 border-2 m-2 border-black'
            value={password}
            onChange={({ target }) => setPassword(target.value)}
            id='password'
          />
        </label>
        <button
          onClick={handleClick}
          type='submit'
          className='px-1 py-0.5 border-2 m-2 border-black'
        >
          Cadastrar
        </button>
      </form>
    </div>
  );
}
